### ISSUE TITLE
Queue-it

### ISSUE THREAD

**Issue by chubchub7087** [max32002/tixcraft_bot#202]
请考虑加入Queue-it 过队系统和支持my.bookmyshow.com 和 thaiticketmajor。谢谢。

**Comment by ganhj99** [comment]
Queue-it is not possible to bypass, however, it is possible to generate large number of browsers to start queue before the event starts, increasing the chance of being in front line of the queue.

For bookmyshow, I will contribute.
For thaiticketmajor, it is harder because it needs to select by seat and is not automatically assigned by the system.

**Comment by chubchub7087** [comment]
@ganhj99 Hi😊,yes you are right, generate a large number of browsers. I'll be very grateful if you can contribute the queue it for ticketmaster.sg (only concerts held at national stadium have queue it) , sistic.sg and bookmyshow? All of them uses queue it so it should be similar right? Thank you so much.

**Comment by ganhj99** [comment]
@chubchub7087 It is possible but do note that you need high compute power CPU in order to achieve that. 
For example, cloud VM/VMs that is able to spin up ~10k browsers (the number of browsers is highly depending on the queue size/demand) together with rotating proxy (will cost around 5USD per GB which can handle ~1k browsers). 

It seems, to achieve this, you will need to bare a certain amount of cost (VM & proxy).

**Comment by chubchub7087** [comment]
@ganhj99 Yup, I'm ok to bare some costs😊 Can you recommend me a proxy provider as the current one im using is abit slow and for aws VM, how many GB of RAM and vCPU should I opt for?

**Comment by ganhj99** [comment]
We have tested with ~100 vCPUs that able to spin up ~1000 browsers (85-90% CPU usage) with standard RAM (2x number of vCPU).
For proxy, smartproxy is quite reliable but is quite expensive (7USD/GB). Otherwise, you may opt for Geonode (4USD/GB). Not tested for other than these 2 proxies.. maybe other people can suggest this?

**Comment by SkrNeymar** [comment]
> We have tested with ~100 vCPUs that able to spin up ~1000 browsers (85-90% CPU usage) with standard RAM (2x number of vCPU). For proxy, smartproxy is quite reliable but is quite expensive (7USD/GB). Otherwise, you may opt for Geonode (4USD/GB). Not tested for other than these 2 proxies.. maybe other people can suggest this?

Hi, I'm very interested in the multi-threaded queuing you're talking about, can you please tell me how I should enable this feature?
